name: Build and deploy to Kuroco front
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
env:
  VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
jobs:    
  #for Push
  pushed_build:
    name: Build(pushed)
    if: (github.repository == 'sagar-paliwal-12/kuroco-svelte-project' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max-old-space-size=16384
      - name: Generate
        run: npm run generate
        # - name: Zip artifact for upload
        #  run: cd dist && zip ../dist.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: build
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://kuroco-svelte-project.g.kuroco.app/direct/menu/github/"
          webhook_secret: "5a58b5be9587ad322aafa60ca136abf5"
          data: '{"single_zip":"0","domain":"kuroco-svelte-project.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'